NodeBB/nodebb-english

plugins/create.rst

Add direct app.js calls for resets

---

installing/os/arch.rst

within arch linux installation guide

npm became **optional** dependency of nodejs.

---

installing/cloud/cloud9.rst
installing/cloud/heroku.rst
installing/cloud/koding.rst
installing/cloud/nitrous.rst
installing/cloud/openshift.rst
installing/os/arch.rst
installing/os/centos.rst
installing/os/debian.rst
installing/os/osx-mavericks.rst
installing/os/smartos.rst
installing/os/ubuntu.rst
installing/os/windows8.rst

Just used a substitution 0.6.x -> 0.7.x. Is it enough?

Use 0.7.x branch on installs

---

configuring/proxies/nginx.rst

This is not present in the docs currently, even though it is recommended as the default method.  
*Note: This is my working base configuration here.*

Added Sample ssl configuration

---

installing/cloud/openshift.rst

Needs confirmation though. It works perfectly for me. ;)

Rewritten and use 0.7.x branch on installs

---

installing/cloud/heroku.rst

Use latest Heroku addon command & NodeBB version

---

installing/docker/nodebb-redis.rst

This update provides easy, convenient and intuitive reading of a code section.

Update nodebb-redis.rst for easy reading.

---

configuring/proxies/nginx.rst

I'm not sure I've put this guide in the right place so feel free to move it to another page if necessary.

Added section on how to configure Nginx to use a custom error page

---

installing/os/freebsd.rst

Instructions for FreeBSD

---

installing/os.rst

It took me a while to find this, until I realized I could go to the document itself, and hit the "edit" link. Ha!

Added link to FreeBSD

---

installing/cloud.rst

New working Codio Link
Old wasn't working anymore.

Link update

---

upgrading/index.rst

Fix numbering on upgrade steps

---

configuring/proxies/nginx.rst

Remove the domain and use the $server_name variable which is already declared.

Use $server_name varialble instead.

---

installing/cloud/openshift.rst

Updated for NodeBB 0.9.x and Mongo

---

plugins/create.rst

https://github.com/NodeBB/NodeBB/pull/4162

Update create.rst, Add CLS docs

---

installing/os/windows8.rst

I added a few things to the windows documentation to allow new users to get NodeBB up and running easier.

Updated windows documentation

---

installing/cloud/openshift.rst

RE: https://github.com/NodeBB/nodebb-english/pull/84#issuecomment-193766091
Thanks @nhlpl

Revert Openshift to v0.9.x

---

plugins/create.rst

added `module.exports = MyPlugin;` to the examples

added module.exports to plugin documentation 

---

installing/cloud/openshift.rst

Removes a tags from appearing on documentation site

Adding a bit more on Openshift Install

---

installing/cloud/openshift.rst

Just noticed I didn't swap out all of the links, my mistake.

Remove a bit of markdown

---

plugins/create.rst

related https://github.com/NodeBB/NodeBB/pull/4787

rm cls for now

---

installing/cloud.rst

Added our guides for installing NodeBB on CentOS and Ubuntu

Added our tutorials

---

installing/cloud.rst
installing/cloud/cloudron.rst

Thanks for NodeBB! We have packaged nodebb for the cloudron and would be great if you could list us as one of the installation methods. I have added a link to the source code as well. Let me know if you have any questions

Add cloudron as an installation option

---

plugins/create.rst

Updating the docs to include instructions on how to link their plugin.

adding Link the plugin

---

configuring/databases/mongo.rst

Hi,
The latest version of MongoDB is 3.2. So, I update some content about it.

Update some content about MongoDB 3.2.x

---

installing/os/ubuntu.rst

I've updated the Ubuntu guide with more context and more thorough instructions. This includes:
-  Updating the guide to use more recent software versions.
-  Removing outdated content around MongoDB 2.6.x.
-  Removing details around non-existent NodeBB branches.
-  Adding additional instruction around MongoDB administration, configuration as well as details around missing permissions for cluster monitoring.
-  Adding a systemd component for managing NodeBB.
I ran through entire setup using my changes and was successful.

Revised Ubuntu guide with more context.
